User model
riveromj/Foodie-App-Backend pull request #2
Opened 2021-01-18 15:19 UTC by VirginiaKMartinez

Creado User_model.

2021-01-18 17:05 UTC, Ped31 approved these changes

2021-01-18 17:51 UTC, rlence commented
revisa la linea 10, en la columna img pusiste db.String y debe ser db.String(numero), el numero es la cantidad de (caracteres) = (letras) que puede almacenar esa columnas, si quieres usar un elemento de guardar string de manera variable puede usar el Text, en este link ves los tipos de datos de sqlalchemy https://docs.sqlalchemy.org/en/13/core/type_basics.html

2021-01-19 18:53 UTC, VirginiaKMartinez commented
> revisa la linea 10, en la columna img pusiste db.String y debe ser db.String(numero), el numero es la cantidad de (caracteres) = (letras) que puede almacenar esa columnas, si quieres usar un elemento de guardar string de manera variable puede usar el Text, en este link ves los tipos de datos de sqlalchemy https://docs.sqlalchemy.org/en/13/core/type_basics.html

--> He cambiado ya ese db.string por db.Text, prefiero algo variable porque los links pueden ser muy largos.

2021-01-19 19:21 UTC, Tozzigh requested changes

2021-01-19 19:21 UTC, Tozzigh commented on src/models.py
> +    user_name = db.Column(db.string(80), unique=True, nullable= False)
string tiene que ser String con s maiuscula.

2021-01-20 09:23 UTC, VirginiaKMartinez commented on src/models.py
> +    user_name = db.Column(db.string(80), unique=True, nullable= False)
Cambiado! me das ok? ;)

2021-01-21 19:45 UTC, Tozzigh approved these changes

2021-01-23 10:34 UTC, merged